# Generated by Django 5.2.5 on 2025-08-27 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alliance', '0002_remove_memberprofile_dob_remove_memberprofile_pob_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caste', models.CharField(max_length=100, unique=True)),
                ('caste_ta', models.CharField(blank=True, help_text='Tamil name', max_length=100)),
            ],
            options={
                'verbose_name': 'Caste',
                'verbose_name_plural': 'Castes',
            },
        ),
        migrations.CreateModel(
            name='Koottam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcaste', models.CharField(max_length=100)),
                ('subcaste_ta', models.CharField(blank=True, help_text='Tamil name', max_length=100)),
                ('caste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='koottams', to='alliance.caste')),
            ],
            options={
                'verbose_name': 'Koottam',
                'verbose_name_plural': 'Koottams',
                'unique_together': {('caste', 'subcaste')},
            },
        ),
        migrations.CreateModel(
            name='FamilyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(blank=True, max_length=200)),
                ('mother_name', models.CharField(blank=True, max_length=200)),
                ('siblings', models.CharField(blank=True, help_text='Comma separated names or count', max_length=200)),
                ('kula_deity', models.CharField(blank=True, max_length=200)),
                ('caste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alliance.caste')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='family_detail', to='alliance.memberprofile')),
                ('koottam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alliance.koottam')),
            ],
        ),
    ]
