# Generated by Django 5.2.5 on 2025-08-27 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alliance', '0003_caste_koottam_familydetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasi', models.CharField(max_length=50, unique=True)),
                ('rasi_ta', models.CharField(blank=True, help_text='Tamil name', max_length=50)),
            ],
            options={
                'verbose_name': 'Rasi',
                'verbose_name_plural': 'Rasis',
            },
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.CharField(max_length=50)),
                ('star_ta', models.CharField(blank=True, help_text='Tamil name', max_length=50)),
                ('rasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stars', to='alliance.rasi')),
            ],
            options={
                'verbose_name': 'Star',
                'verbose_name_plural': 'Stars',
                'unique_together': {('rasi', 'star')},
            },
        ),
        migrations.CreateModel(
            name='BirthDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('time_of_birth', models.TimeField(blank=True, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=200)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='birth_detail', to='alliance.memberprofile')),
                ('rasi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alliance.rasi')),
                ('star', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alliance.star')),
            ],
        ),
    ]
