# Generated by Django 5.2.5 on 2025-08-30 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alliance', '0005_education_profession_professionaldetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dhosam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dhosam', models.CharField(max_length=50, unique=True)),
                ('dhosam_ta', models.CharField(blank=True, help_text='Tamil name', max_length=50)),
            ],
            options={
                'verbose_name': 'Dhosam',
                'verbose_name_plural': 'Dhosams',
            },
        ),
    ]
