# Generated by Django 5.2.5 on 2025-08-30 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alliance', '0006_dhosam'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthdetail',
            name='dhosam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alliance.dhosam'),
        ),
    ]
