# Generated by Django 5.2.5 on 2025-09-07 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alliance', '0008_profilephoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('message_ta', models.TextField(blank=True, help_text='Message in Tamil')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
