# Generated by Django 5.2.5 on 2025-09-07 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alliance', '0009_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shortlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('favorite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='alliance.memberprofile')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlists', to='alliance.memberprofile')),
            ],
            options={
                'unique_together': {('member', 'favorite')},
            },
        ),
    ]
